# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sDraw
                                 A QGIS plugin
 This plugin draws spatially ballanced samples
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-03
        copyright            : (C) 2019 by Jared Spaulding - WEST
        email                : jspaulding@west-inc.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sDraw class from file sDraw.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .s_draw import sDraw
    return sDraw(iface)
